/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.registration.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static student.registration.system.mysqlConnection.conn;
import static student.registration.system.registeredStudents.rs;

/**
 *
 * @author Hassow099
 */
public class studentManagement extends javax.swing.JFrame {

    /**
     * Creates new form studentManagement
     */
     private  static Connection conn;
    private  static Statement st;
    private  static PreparedStatement pst;
    private  static ResultSet rs;
    
    static  String regno;
    static  String name;
    public studentManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1Department = new javax.swing.JComboBox<>();
        jComboBox2Faculty = new javax.swing.JComboBox<>();
        jComboBox3Gender = new javax.swing.JComboBox<>();
        regnoField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fathersNameField = new javax.swing.JTextField();
        AgejComboBox4 = new javax.swing.JComboBox<>();
        RegisterNewStudBtn = new javax.swing.JButton();
        jComboBox5CourseName = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        DeleteRecordBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtRegStudentsOnMngnt = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(51, 255, 255));
        jPanel4.setForeground(new java.awt.Color(204, 0, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STUDENT MANAGEMENT SYSTEM");

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Registered Students");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Add New Students");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 0));
        jButton3.setText("Process Results");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 0, 204));
        jButton4.setText("Register a Course");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 153, 0));
        jButton5.setText("Promote Students");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Faculty");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Department");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Course Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Reg No.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Gender");

        jComboBox1Department.setBackground(new java.awt.Color(0, 153, 153));
        jComboBox1Department.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1Department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DCSC", "DASC", "DC", "DBM", "DAGR", "DPSY", "DMATH", "DHUM" }));

        jComboBox2Faculty.setBackground(new java.awt.Color(0, 153, 153));
        jComboBox2Faculty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2Faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FSET", "FBUST", "FERED", "FLAW", " " }));

        jComboBox3Gender.setBackground(new java.awt.Color(0, 153, 153));
        jComboBox3Gender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox3Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "Other" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Father's Name");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Age");

        AgejComboBox4.setBackground(new java.awt.Color(0, 153, 153));
        AgejComboBox4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AgejComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39" }));

        RegisterNewStudBtn.setBackground(new java.awt.Color(0, 153, 153));
        RegisterNewStudBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RegisterNewStudBtn.setForeground(new java.awt.Color(255, 0, 51));
        RegisterNewStudBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/registration/system/icons/Save-icon_1_1.png"))); // NOI18N
        RegisterNewStudBtn.setText("Save");
        RegisterNewStudBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterNewStudBtnActionPerformed(evt);
            }
        });

        jComboBox5CourseName.setBackground(new java.awt.Color(0, 153, 153));
        jComboBox5CourseName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox5CourseName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Python", "JAVA DESKTOP APPLICATION", "WEB ADMINISTRATION", "DATABASE MANAGEMENT", "RESEARCH METHODS", "DATA STRUCTURES" }));
        jComboBox5CourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5CourseNameActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 0, 51));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/registration/system/icons/logout_1_1.png"))); // NOI18N
        jButton6.setText("Log Out");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        UpdateBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UpdateBtn.setForeground(new java.awt.Color(0, 102, 102));
        UpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/registration/system/icons/update icon_1.png"))); // NOI18N
        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        DeleteRecordBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DeleteRecordBtn.setForeground(new java.awt.Color(0, 102, 102));
        DeleteRecordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/registration/system/icons/delete_16x16.gif"))); // NOI18N
        DeleteRecordBtn.setText("Delete");
        DeleteRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRecordBtnActionPerformed(evt);
            }
        });

        ResetBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResetBtn.setForeground(new java.awt.Color(0, 102, 102));
        ResetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/registration/system/icons/erase-128.png"))); // NOI18N
        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        jtRegStudentsOnMngnt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RegNo", "Name", "Course", "Gender", "Faculty", "Department", "FathersNAme", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtRegStudentsOnMngnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtRegStudentsOnMngntMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtRegStudentsOnMngnt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2Faculty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1Department, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox5CourseName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(regnoField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox3Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AgejComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
                            .addComponent(fathersNameField)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DeleteRecordBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ResetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RegisterNewStudBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(86, 86, 86)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1Department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jComboBox5CourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(fathersNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AgejComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(regnoField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(92, 92, 92))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(RegisterNewStudBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteRecordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new registeredStudents().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     new ResultsProcessing().setVisible(true);
     dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       new ResultsProcessing().setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new registeredStudents().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void RegisterNewStudBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterNewStudBtnActionPerformed
    String faculty=(String)jComboBox2Faculty.getSelectedItem();
    String department=(String)jComboBox1Department.getSelectedItem();
    String Course=(String)jComboBox5CourseName.getSelectedItem();   
    String regno=regnoField.getText();
    String name=nameField.getText();
    String gender=(String)jComboBox3Gender.getSelectedItem(); 
    String fname=fathersNameField.getText(); 
    String age=(String)AgejComboBox4.getSelectedItem(); 
  
         try {
             Class.forName("com.mysql.jdbc.Driver");
            conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/dbchuka" ,"root","");
             st=conn.createStatement();
             while(regno!=""){
             st.executeUpdate("INSERT INTO tbstudents (faculty,department,program,regno,firstname,gender,lastname,age)"
                     + "VALUES('"+faculty+"','"+department+"','"+Course+"','"+regno+"','"+name+"','"+gender+"','"+fname+"','"+age+"')");
             fetchAllStudents();        
             JOptionPane.showMessageDialog(null,name+"'s Record Added");

             insertLoginDetailsToo();
             }
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null,"Unable to add Record to tbstudents!");
         }
    }//GEN-LAST:event_RegisterNewStudBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        regnoField.setText(""); 
        nameField.setText(""); 
        jComboBox5CourseName.setSelectedItem(0);   
        jComboBox3Gender.setSelectedItem(0);  
        jComboBox2Faculty.setSelectedItem(0); 
        jComboBox1Department.setSelectedItem(0);
        fathersNameField.setText(""); 
        AgejComboBox4.setSelectedItem(0);
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void DeleteRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRecordBtnActionPerformed
        DefaultTableModel tbmdl =(DefaultTableModel)jtRegStudentsOnMngnt.getModel();
        int selectedRow=jtRegStudentsOnMngnt.getSelectedRow();    
        
        try{
            int id =Integer.parseInt(tbmdl.getValueAt(selectedRow,0).toString());
            int delete=JOptionPane.showConfirmDialog(null,"Confirm You want to delete this Record","warning!",
                    JOptionPane.YES_NO_OPTION);
            
      if(delete==JOptionPane.YES_OPTION){           
            Class.forName("com.mysql.jdbc.Driver");
            conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/dbchuka" ,"root","");
             pst=conn.prepareStatement("Delete from tbstudents where id=?");
              
              pst.setInt(1,id);
              pst.executeUpdate();      
             JOptionPane.showMessageDialog(null,"Record Deleted!");
             fetchAllStudents();
             
                regnoField.setText(""); 
                nameField.setText(""); 
                jComboBox5CourseName.setSelectedItem(0);   
                jComboBox3Gender.setSelectedItem(0);  
                jComboBox2Faculty.setSelectedItem(0); 
                jComboBox1Department.setSelectedItem(0);
                fathersNameField.setText(""); 
                AgejComboBox4.setSelectedItem(0);
            
           
            }
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null,"Unable to add Record to tbstudents!");
         } 
    }//GEN-LAST:event_DeleteRecordBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
         //VIEW  All Registered Students
        try {
                  conn=mysqlConnection.getConnection();        
                    mysqlConnection.st=conn.createStatement(); 
             String query=("SELECT *FROM tbstudents");
                    rs=mysqlConnection.st.executeQuery(query);
                   
            while(rs.next()){
               String id=rs.getString("id");
              regno=rs.getString("RegNO");
              String name=rs.getString("FirstName");
              String course=rs.getString("Program");   
              String gender=rs.getString("Gender");
              String faculty=rs.getString("Faculty"); 
              String department=rs.getString("Department");
              String fathersName=rs.getString("LastName");
              String Age=rs.getString("Age");


                     
                  String tbData[]={id,regno,name,course,gender,faculty,department,fathersName,Age};
             
                  
                  DefaultTableModel tbmdl =(DefaultTableModel)jtRegStudentsOnMngnt.getModel();
                  tbmdl.addRow(tbData); 

                   }
                   conn.close();
               } catch (SQLException ex) {
                   System.out.println("failed table reading!");
               }       
        
    }//GEN-LAST:event_formComponentShown

    private void jComboBox5CourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5CourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5CourseNameActionPerformed

    private void jtRegStudentsOnMngntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtRegStudentsOnMngntMouseClicked
        DefaultTableModel tbmdl =(DefaultTableModel)jtRegStudentsOnMngnt.getModel();
        int selectedRow=jtRegStudentsOnMngnt.getSelectedRow();
        try{
        regnoField.setText(tbmdl.getValueAt(selectedRow,1).toString()); 
        nameField.setText(tbmdl.getValueAt(selectedRow,2).toString()); 
        jComboBox5CourseName.setSelectedItem(tbmdl.getValueAt(selectedRow,3).toString());   
        jComboBox3Gender.setSelectedItem(tbmdl.getValueAt(selectedRow,4).toString());  
        jComboBox2Faculty.setSelectedItem(tbmdl.getValueAt(selectedRow,5).toString()); 
        jComboBox1Department.setSelectedItem(tbmdl.getValueAt(selectedRow,6).toString());
        fathersNameField.setText(tbmdl.getValueAt(selectedRow,7).toString()); 
        AgejComboBox4.setSelectedItem(tbmdl.getValueAt(selectedRow,8).toString());  
        }catch(Exception e){
            System.out.println("");
        }
    }//GEN-LAST:event_jtRegStudentsOnMngntMouseClicked

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tbmdl =(DefaultTableModel)jtRegStudentsOnMngnt.getModel();
        int selectedRow=jtRegStudentsOnMngnt.getSelectedRow();
        
        try {
            int id =Integer.parseInt(tbmdl.getValueAt(selectedRow,0).toString());
            
            Class.forName("com.mysql.jdbc.Driver");
            conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/dbchuka" ,"root","");
             pst=conn.prepareStatement("Update tbstudents SET RegNO=?,firstname=?,course=?,gender=?,faculty=?,department=?,lastname=?,age=?"
                     + "where id=?");
             
            pst.setString(1,regnoField.getText());  
            pst.setString(2,nameField.getText());
            pst.setString(3,(String)jComboBox5CourseName.getSelectedItem());   
            pst.setString(4,(String)jComboBox3Gender.getSelectedItem());  
            pst.setString(5,(String)jComboBox2Faculty.getSelectedItem());  
            pst.setString(6,(String)jComboBox1Department.getSelectedItem());  
            pst.setString(7,fathersNameField.getText());
            pst.setString(8,(String)AgejComboBox4.getSelectedItem());
            pst.setInt(9,id);
            
            pst.executeUpdate();
       
             JOptionPane.showMessageDialog(null,"Record Updated");
           fetchAllStudents();
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null,"Unable to add Record to tbstudents!");
         } 
        
        
    }//GEN-LAST:event_UpdateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentManagement().setVisible(true);
            }
        });
    }
    private void fetchAllStudents(){
 //VIEW  All Registered Students
        try {
                  conn=mysqlConnection.getConnection();        
                    mysqlConnection.st=conn.createStatement(); 
             String query=("SELECT *FROM tbstudents");
                    rs=mysqlConnection.st.executeQuery(query);
                   
            while(rs.next()){
              String id=rs.getString("ID");
             String regno=rs.getString("RegNO");
              String name=rs.getString("FirstName");
              String course=rs.getString("Program");   
              String gender=rs.getString("Gender");
              String faculty=rs.getString("Faculty"); 
              String department=rs.getString("Department");


                     
                  String tbData[]={id,regno,name,course,gender,faculty,department};
             
                  
                  DefaultTableModel tbmdl =(DefaultTableModel)jtRegStudentsOnMngnt.getModel();
                  tbmdl.addRow(tbData); 

                   }
                   conn.close();
               } catch (Exception ex) {
                   System.out.println("failed table reading!");
               }       
}
    public void insertLoginDetailsToo(){
     try {
             //save login details too
              conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/dbchuka" ,"root","");
             st=conn.createStatement();
           String sql2=("INSERT INTO studentloginaccounts (username,regno)VALUES('"+name+"','"+regno+"')");
         st.execute(sql2);
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null, "login details not updated");
         }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AgejComboBox4;
    private javax.swing.JButton DeleteRecordBtn;
    private javax.swing.JButton RegisterNewStudBtn;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JTextField fathersNameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1Department;
    private javax.swing.JComboBox<String> jComboBox2Faculty;
    private javax.swing.JComboBox<String> jComboBox3Gender;
    private javax.swing.JComboBox<String> jComboBox5CourseName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtRegStudentsOnMngnt;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField regnoField;
    // End of variables declaration//GEN-END:variables
}
